sudo: required
services:
  - docker

before_install:
  - docker build -t kotadd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kotadd/react-test npm test -- --coverage

after_success:
  - docker build -t kotadd/multi-client ./client
  - docker build -t kotadd/multi-nginx ./nginx
  - docker build -t kotadd/multi-server ./server
  - docker build -t kotadd/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kotadd/multi-client
  - docker push kotadd/multi-nginx
  - docker push kotadd/multi-server
  - docker push kotadd/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-565523124642
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
