sudo: required
services:
  - docker

before_install:
  - docker build -t kotadd/react-test -f ./client/Dockerfile.dev

script:
  - docker run kotadd/react-test npm test -- --coverage

after_success:
  - docker build -t kotadd/multi-client ./client
  - docker build -t kotadd/multi-nginx ./nginx
  - docker build -t kotadd/multi-server ./server
  - docker build -t kotadd/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub